language: php
php:
  - 5.4
services:
  - mysql
script:
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - mysql create database nf_acceptance_tests
  - bash run-tests.sh