language: php
php:
  - 5.4
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE nf_acceptance_tests;'
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
script:
  - bash run-tests.sh -s -b master